spring:
  profiles:
    active: default
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 172143
    url: jdbc:postgresql://localhost:5432/classifiers?currentSchema=classifiers
    port: 5432
    driver-class-name: org.postgresql.Driver
server:
  port: 81

users:
  service:
    url: http://localhost:82/api/v1/users/me

---
spring:
  profiles: production
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://db:5432/classifiers?currentSchema=classifiers
server:
  port: 81
users:
  service:
    url: http://user-service:82/api/v1/users/me
