spring:
  jpa:
    database: POSTGRESQL
      properties:
        hibernate:
          ddl_auto: none
          show_sql: true
          format_sql: true
  datasource:
    username: postgres
    password: 172143
    url: jdbc:postgresql://localhost:5432/events?currentSchema=afisha
    port: 5432
    driver-class-name: org.postgresql.Driver

server:
  port: 80
