spring:
  profiles:
    active: @profileActive@
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 172143
    url: jdbc:postgresql://localhost:5432/events?currentSchema=afisha
    port: 5432
    driver-class-name: org.postgresql.Driver
server:
  port: 80

users:
  service:
    url: http://localhost:82/api/v1/users/me

country:
  service:
    url: http://localhost:81/api/v1/classifier/country/

category:
  service:
    url: http://localhost:81/api/v1/classifier/concert/category/

---
spring:
  config:
    activate:
      on-profile:
        - production
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://db:5432/events?currentSchema=afisha

users:
  service:
    url: http://user-service:82/api/v1/users/me

country:
  service:
    url: http://classifier-service:81/api/v1/classifier/country/

category:
  service:
    url: http://classifier-service:81/api/v1/classifier/concert/category/