spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 172143
    url: jdbc:postgresql://localhost:5432/users?currentSchema=security
    port: 5432
    driver-class-name: org.postgresql.Driver

server:
  port: 82